name: flutter_timetable_view
description: Timetable Widget Package for for Flutter
version: 0.2.0
homepage: https://github.com/yamarkz

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
